version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=187d9f42d9eb77116613f71a2a4465b73b54ade22f2fce1988c4e1b7df525391
      - N8N_HOST=n8n
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
      - NODE_ENV=production
      # (опционально) включи Basic Auth:
      - N8N_BASIC_AUTH_ACTIVE=false
      # - N8N_BASIC_AUTH_USER=admin
      # - N8N_BASIC_AUTH_PASSWORD=secret
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./data:/data  # для доступа к knowledge_base.json и т.п.
      - ./workflows:/workflows
    depends_on:
      - qdrant

  postgres:  
    image: postgres:17  
    container_name: bsuir-postgres  
    env_file:  
      - postgres.env  
    ports:  
      - "5432:5432"  
    volumes:  
      - postgres_data:/var/lib/postgresql/data/  
      - ./test_sql_scripts/dumps:/docker-entrypoint-initdb.d  
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]  
      interval: 5s  
      timeout: 5s  
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: bsuir-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"      # REST API
      # - "6334:6334"      # gRPC (опционально, можно закомментировать если не нужен)
    volumes:
      - qdrant_storage:/qdrant/storage

  telegram-client:
    image: ghcr.io/semantic-hallucinations/uma-telegram-client:main-2025-12-19-15h40m
    container_name: telegram-client
    env_file:
      - telegram-client.env
  
  mcp-server:
    image: ghcr.io/semantic-hallucinations/uma-mcp-server:main-2025-12-18-23h58m
    container_name: mcp-server
    ports: 
      - "8000:8000"
    env_file:
      - mcp-server.env

  lightrag:
    image: ghcr.io/hkuds/lightrag:v1.4.9.8-lite # Или соберите из исходников, если используете кастомную версию
    container_name: lightrag
    ports:
      - "9621:9621"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - ./lightrag_data:/app/data
    env_file:
      - lightrag.env

volumes:
  qdrant_storage:
  postgres_data:
  lightrag_data:
